# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # This build job generates the project build/ with frozen flask,
  # and uploads it as an artifact so other jobs can use it
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Freeze application with frozen_flask
        run: |
          python freeze.py
      #- name: Replace URL's with 2023.nerdear.la prefix
      #  run: |
      #    bash scripts/replace_refs_with_subdomain.sh
      # GITHUB PAGES HERE
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Show ls result
        run: ls
      - name: Show ls app
        run: ls app/
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./app/build/"
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v2
